// Components
import { Header, Footer } from "@/components/layout";
import { StepperContextProvider, BuilderContextProvider } from "@/contexts";

// Styles
import "@/styles/index.scss";
import "@/components/steps/Steps.scss";
import { Metadata } from "next";
import Head from "next/head";

// SEO
export const metadata: Metadata = {
  title: "Product Builder",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css?family=Lato:400,700&display=optional"
          rel="stylesheet"
        />
      </Head>
      <body>
        <StepperContextProvider>
          <BuilderContextProvider>
            <div className="cd-product-builder">
              <Header />
              <div className="cd-builder-steps">{children}</div>
              <Footer />
            </div>
          </BuilderContextProvider>
        </StepperContextProvider>
      </body>
    </html>
  );
}
