"use client";

// Components
import { Header, Footer } from "@/components/layout";
import { StepperContextProvider, BuilderContextProvider } from "@/contexts";

// Styles
import "@/styles/index.scss";
import "@/components/steps/Steps.scss";
import { Metadata } from "next";
import { useStepper } from "@/hooks/useStepper";
import { useBuilder } from "@/hooks/useBuilder";

// SEO
export const metadata: Metadata = {
  title: "Product Builder",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { currentStepId, steps } = useStepper();
  const {
    current: { selectedCar },
    error,
  } = useBuilder();

  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css?family=Lato:400,700"
          rel="stylesheet"
        />
      </head>
      <body>
        <StepperContextProvider>
          <BuilderContextProvider>
            <div className="cd-product-builder">
              <Header />
              <div className="cd-builder-steps">{children}</div>
              <Footer
                selectedCar={selectedCar}
                error={error}
                currentStepId={currentStepId}
                steps={steps}
              />
            </div>
          </BuilderContextProvider>
        </StepperContextProvider>
      </body>
    </html>
  );
}
